apiVersion: v1
kind: Pod
metadata:
  name: lobotomist
  namespace: bots
  labels:
    type: bot
    target: discord
spec:
  containers:
  - name: lobotomist
    image: registry.digitalocean.com/medheav/lobotomist:latest
    env:
    - name: DISCORD_TOKEN
      valueFrom:
        secretKeyRef:
          name: lobotomist
          key: discord_token
