apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobotomist
  namespace: bots
  labels:
    type: bot
    target: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      type: bot
  template:
    metadata:
      labels:
        type: bot
        target: discord
    spec:
      containers:
        - name: lobotomist
          image: registry.digitalocean.com/medheav/lobotomist:latest
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lobotomist
                  key: discord_token
